### ISSUE TITLE
Better start and finish view

### ISSUE THREAD

**Issue by erydberg** [erydberg/gokopen#4]
So that it can be easier for the ones working in start and goal-areas giving them an overview of all the patrols.

**Comment by erydberg** [comment]
Working on it in the startfinish-branch.

**Comment by apikas** [comment]
Excellent!

**Comment by erydberg** [comment]
@apikas I've an almost working version on a start-finish-page. Can you take a look and see if this is something that you'll find useful? The status information, if a patrol is out walking, waiting, or reached the finish-line (or indeed has resigned) is shown in the first column. When you click on the icon you move the patrol to the next status (it moves from registered - active - finished - resigned and then back again to registered, one step on each click).

**Comment by apikas** [comment]
Nice, I will have a look when I get home. On vacation this week.

**Comment by erydberg** [comment]
Implemented.
