### ISSUE TITLE
Exportera resultat

### ISSUE THREAD

**Issue by riccla0321** [erydberg/gokopen#62]
Det hade varit riktigt najs att kunna exportera resultat som en CSV, TXT eller XLS-fil, för att underlätta importering av resultat i andra system och dokument.

**Comment by erydberg** [comment]
Nu finns en funktion för att exportera ut resultaten till en csv-fil (som öppnas korrekt i excel). Den första versionen exporterar ut en resultatlista sorterad efter gren och placering med följande värden:
patrullnamn, kår, summan av poängen på alla kontroller, summan av alla stilpoäng samt totalsumman. 

Jag tittar på att få en bra export med alla resultat, nedbrutet per kontroll också.
