### ISSUE TITLE
Begränsa längd på patrullnamn för att få snyggare utskrifter

### ISSUE THREAD

**Issue by kallemooo** [erydberg/gokopen#71]
Blir patrullnamnen för långa så blir formateringen av utskrifterna för startkort och kontrollistor konstig.

För startkorten (små startkort) hamnar de inte i linje med varandra och ger utskrifter där korten är förskjutna ifrån varandra.

**Comment by erydberg** [comment]
Ändrat så patrullnamn alltid har "två rader" på de små startkorten, är namnet långt tas bara de 35 första tecknen med i utskriften och så läggs ... på för att indikera att det är ett ännu längre namn.
Tagit tillfället i akt att justera i texterna något för att ge bättre plats.
