### ISSUE TITLE
För långt namn på kontroll ger två rader som startplats på litet startkort

### ISSUE THREAD

**Issue by kallemooo** [erydberg/gokopen#72]
När startplats läggs in och kontrollnamnet är för långt ger det två rader på startkortet.

När det sker borde alla startkorten skrivas ut med två rader reserverade för startplats.

**Comment by erydberg** [comment]
Valde att minska teckenstorleken och bara ha det på en rad och bara skriva ut så många tecken som får plats. Om både patrull och startplats är dubbelrader kan nog korten bli för långa. (Har ingen skrivare tillgänglig just nu för att kolla ordentligt.)
