### ISSUE TITLE
Ändra när man skapar patrull så är klass inte ifyllt som standard

### ISSUE THREAD

**Issue by kallemooo** [erydberg/gokopen#73]
När man lägger till en patrull är idag klass förifyllt till första klassen i listan.
Det gör att när patruller i andra klasser läggs in så blir det ibland fel klass vald.

Ändra så att om det är mer än en klass är inte klass förifyllt och måste väljas.

**Comment by erydberg** [comment]
Fixat detta i "självregistreringen" och patrullhanteringen under administration. Kan det finnas något mer ställe?
