### ISSUE TITLE
På adminsidan för patruller är det för enkelt att radera en patrull

### ISSUE THREAD

**Issue by kallemooo** [erydberg/gokopen#74]
Kryssrutan för att radera patrull är längs till höger där man rullningslisten är. Det gör det lite för enkelt att råka radera en patrull.
Då man inte får nån fråga så ser man inte alltid att en patrull raderades.

Ändra så att man får en fråga om patrullen ska raderas.

**Comment by erydberg** [comment]
Lagt in en kontroll när man klickar på ta bort-patrull-knappen så man kan svara ja eller avbryt.
